---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eks-demo
  name: deployment-eks-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-eks-demo
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-eks-demo
    spec:
      containers:
      - image: CONTAINER_IMAGE
        imagePullPolicy: Always
        name: app-eks-demo
        ports:
        - containerPort: 80
 ---
apiVersion: v1
kind: Service
metadata:
  name: jaheda-service
spec:
  type: LoadBalancer
  selector:
    app: app-eks-demo
  ports:
    - port: 80
      targetPort: 80


